import * as pen from '.'

console.log( pen.blue( `Hello, ${ pen.bold( 'World' ) }!!!` ) )

console.log( pen.reset( 'reset' ) )
console.log( pen.bold( 'bold' ) )
console.log( pen.italic( 'italic' ) )
console.log( pen.underline( 'underline' ) )
console.log( pen.inverse( 'inverse' ) )
console.log( 'hidden[', pen.hidden( 'hidden' ), ']' )
console.log( pen.strikethrough( 'strikethrough' ) )
console.log( pen.gray( 'gray' ) )
console.log( pen.red( 'red' ) )
console.log( pen.green( 'green' ) )
console.log( pen.yellow( 'yellow' ) )
console.log( pen.blue( 'blue' ) )
console.log( pen.magenta( 'magenta' ) )
console.log( pen.cyan( 'cyan' ) )
console.log( pen.white( 'white' ) )
console.log( pen.bgRed( 'bgRed' ) )
console.log( pen.bgGreen( 'bgGreen' ) )
console.log( pen.bgYellow( 'bgYellow' ) )
console.log( pen.bgBlue( 'bgBlue' ) )
console.log( pen.bgMagenta( 'bgMagenta' ) )
console.log( pen.bgCyan( 'bgCyan' ) )
console.log( pen.bgWhite( 'bgWhite' ) )
